version: '3.9'

services:

  mysql-db-3308:
    image: mysql
    container_name: mysql-db-3308
    networks:
      - adr-list-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: adr_list_2
      MYSQL_USER: adrlists
      MYSQL_PASSWORD: adrlists
    ports:
      - "3308:3306"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: adr-list
    ports:
      - "8090:8090"
    restart: on-failure
    networks:
      - adr-list-mysql
    depends_on:
      - mysql-db-3308
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-3308:3306/adr_list_2?autoReconnect=true&useSSL=false&maxReconnects=10&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: adrlists
      SPRING_DATASOURCE_PASSWORD: adrlists
      SLEEP_LENGTH: 5
      WAIT_HOSTS: mysql-db-3308:3308
    tty: true
    stdin_open: true

networks:
  adr-list-mysql:
    driver: bridge