version: '3.8'

services:

  mysql-db-3308:
    image: mysql:8
    container_name: mysql-db-3308
    networks:
      - adr-list-mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3308:3306"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: adr-list
    ports:
      - "8090:8090"
    restart: on-failure
    networks:
      - adr-list-mysql
    depends_on:
      - mysql-db-3308
    env_file:
      - ./.env
    tty: true
    stdin_open: true

networks:
  adr-list-mysql:
    driver: bridge