insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Yambee', '44 Clarendon Court', '765 02', 'Otrokovice', '+420 827 667 2354', 'btissiman0@noaa.gov', 'Booth Tissiman', '59-478-6950', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active, country) values ('Leenti', '60 Prairieview Point', '55-011', 'Nagrog Wetan', '+62 886 836 0474', 'dkeatch1@ibm.com', 'Doris Keatch', '37-318-6297', 1, 'POOOOLAND');
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Yodoo', '66 Alpine Plaza', null, 'Kunmi Erdi', '+86 397 505 6821', 'sdensham2@patch.com', 'Sashenka Densham', '33-430-6517', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Rhynyx', '175 Superior Drive', '663914', 'Ol’ginskaya', '+7 998 210 3764', 'kthornebarrow3@reference.com', 'Kathrine Thornebarrow', '85-700-1271', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Twitterworks', '67 6th Court', '62304 CEDEX', 'Lens', '+33 335 448 1239', 'bcrate4@wsj.com', 'Bernarr Crate', '23-676-2743', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Yacero', '96 Merry Street', null, 'Batudulang', '+62 795 302 7745', 'jlalor5@comsenz.com', 'Jeremias Lalor', '57-538-3880', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Eidel', '2285 Waxwing Circle', null, 'Henglishan', '+86 781 938 9486', 'kpinnion6@zimbio.com', 'Kristyn Pinnion', '24-940-2475', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Tambee', '0153 Sycamore Place', '2442', 'Wañgan', '+63 198 620 0928', 'smcgrudder7@unesco.org', 'Sadella McGrudder', '93-931-9085', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Topicshots', '5975 Westridge Place', '9113', 'Florentino Ameghino', '+54 506 481 9543', 'qdenacamp8@shinystat.com', 'Quentin Denacamp', '83-564-0008', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Trupe', '01583 Moose Center', '4023', 'San Pedro', '+63 601 491 5241', 'astutt9@spiegel.de', 'Angelina Stutt', '90-363-7816', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Bubbletube', '416 Sunfield Point', null, 'Erong', '+86 235 165 2706', 'lbettona@amazon.co.jp', 'Lise Betton', '41-602-5816', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Oyoba', '8399 Waubesa Plaza', null, 'Oleksandriya', '+380 854 286 0553', 'lsichab@forbes.com', 'Lew Sicha', '20-519-3674', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Jabbertype', '55 Morningstar Crossing', null, 'Luangwa', '+260 959 803 3257', 'bmohammadc@china.com.cn', 'Bengt Mohammad', '46-153-3067', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Oyope', '20331 Spohn Drive', null, 'Chandmanĭ', '+976 224 162 0151', 'kconninghamd@topsy.com', 'Kaitlin Conningham', '53-911-8455', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Gigashots', '23 Pawling Circle', null, 'Geneng Tengah', '+62 840 900 2761', 'nlathleiffuree@mayoclinic.com', 'Natividad Lathleiffure', '05-201-7350', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Izio', '22052 Bartillon Parkway', '4399', 'Ndwedwe', '+27 807 328 1608', 'icoslettf@comsenz.com', 'Inness Coslett', '06-095-3116', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Roomm', '20 Buell Pass', '0984', 'Oslo', '+47 839 447 7149', 'gtanguyg@harvard.edu', 'Giulia Tanguy', '44-490-6904', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Skajo', '123 Mifflin Way', null, 'Bayt Sāḩūr', '+970 858 409 9085', 'bwallwoodh@cdbaby.com', 'Beverie Wallwood', '16-176-9964', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Jazzy', '93 Sullivan Parkway', null, 'Munjungan', '+62 756 386 7011', 'msoutherni@miibeian.gov.cn', 'Mordecai Southern', '79-276-9705', 1);
insert into companies (name, address, postcode, city, phone, email, person_contact, reference_no, is_active) values ('Zoomcast', '51141 Judy Plaza', '34-322', 'Gilowice', '+48 425 649 0210', 'fabrahmsonj@youku.com', 'Frasquito Abrahmson', '24-103-4863', 1);
#
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('maecenas', 'cdavidovitch0@dedecms.com', 'Carolin', 'Davidovitch', 'xA81qir9', 8, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('elementum in', 'ndalman1@hexun.com', 'Nathaniel', 'Dalman', 'CxPhjhC6Orp0', 2, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('orci eget', 'biceton2@wikia.com', 'Bonnee', 'Iceton', 'XOuIbWtyn5s', 9, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('ultrices posuere cubilia', 'atremaine3@sphinn.com', 'Anjanette', 'Tremaine', 'iDV6gLiV', 5, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('eget nunc', 'ptixall4@edublogs.org', 'Paten', 'Tixall', 'm5BN8G3cqC', 8, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('purus', 'rbridgens5@com.com', 'Rivalee', 'Bridgens', 'tV6Gb4', 4, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('ultrices posuere', 'tjeanel6@naver.com', 'Teirtza', 'Jeanel', 'Kim8DaPp', 8, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('molestie nibh in', 'wprahl7@vimeo.com', 'Wainwright', 'Prahl', 'DrGMDy11o', 1, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('neque duis', 'hdabling8@arizona.edu', 'Harmony', 'Dabling', 'r0Bqqa1zdS', 7, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('enim', 'jrapps9@twitter.com', 'Jan', 'Rapps', 'DYdbnvbZb', 5, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('iaculis congue vivamus', 'mabramowitza@weebly.com', 'Milicent', 'Abramowitz', 'e2BZYss7v', 5, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('vitae consectetuer eget', 'bnindb@businessinsider.com', 'Barney', 'Nind', 'YxbVPacTWqlw', 9, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('tincidunt', 'mwattamc@tinyurl.com', 'Minne', 'Wattam', 'aCRlxCNbY8', 2, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('sit amet', 'omanolovd@mapquest.com', 'Obadias', 'Manolov', '8DoH3U1TeB', 1, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('sed lacus morbi', 'arouthame@com.com', 'Ardisj', 'Routham', 'e8oxVmjjxjp7', 7, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('id', 'cstuckleyf@wufoo.com', 'Corbin', 'Stuckley', 'JDYIjsvY', 2, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('pede justo lacinia', 'qgrigorushking@51.la', 'Quincy', 'Grigorushkin', 'ZAB1V8F5Nsv', 2, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('purus phasellus', 'hdriversh@digg.com', 'Haleigh', 'Drivers', 'LWG3e6k65', 8, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('aliquam non mauris', 'everheijdeni@nsw.gov.au', 'Edna', 'Verheijden', 'qby2V0Q5', 1, 0, 1);
# insert into users_company (description_user, email, first_name, last_name, password_user, company_id, is_super_admin, is_active) values ('elit ac nulla', 'lgornallj@shinystat.com', 'Lauree', 'Gornall', 'QE5dcCl', 10, 0, 1);


insert into customers (address, city, name, email, person_contact, phone, postcode, company_id, is_active) values ('98 Shasta Street', 'Lapai', 'Sandoz Inc', 'rchurly0@constantcontact.com', 'Cléa', '725-493-5597', null, 1, 1);
insert into customers (address, city, name, email, person_contact, phone, postcode, company_id, is_active) values ('7 Northwestern Pass', 'Phu Phiang', 'Nibec Co., Ltd', 'drouthorn1@businessweek.com', 'Estève', '276-301-8061', '10250', 2, 1);
insert into customers (address, city, name, email, person_contact, phone, postcode, company_id, is_active) values ('463 John Wall Terrace', 'Beijiang', 'Qualitest Pharmaceuticals', 'rvedikhov2@amazon.co.uk', 'Andrée', '951-492-5557', null, 5, 1);
insert into customers (address, city, name, email, person_contact, phone, postcode, company_id, is_active) values ('2 Arizona Drive', 'Jastrzębia', 'Morton Grove Pharmaceuticals, Inc.', 'lcharity3@bloglovin.com', 'Mélanie', '923-489-5776', '26-631', 4, 1);
insert into customers (address, city, name, email, person_contact, phone, postcode, company_id, is_active) values ('7694 Melby Point', 'San Fernando de Atabapo', 'Marco Pharma International LLC.', 'jhaskur4@unblog.fr', 'Bécassine', '216-235-4147', null, 8, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('00821 Continental Terrace', 'Vimmerby', 'Laboratoires Dermo Cosmetik Inc.', 'lstefanovic5@dagondesign.com', 'Esbjörn', '724-852-0974', '598 24', 7, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('25732 Northwestern Hill', 'Dimitrov', 'Cintas', 'mletertre6@msn.com', 'Irène', '280-806-0739', null, 7, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('6254 Bayside Road', 'Trollhättan', 'REMEDYREPACK INC.', 'bmussett7@go.com', 'Camélia', '967-768-2020', '461 25', 6, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('8818 East Terrace', 'Skövde', 'HEB', 'gbachmann8@omniture.com', 'Publicité', '791-649-1392', '541 70', 5, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('1974 Bunker Hill Park', 'Padangbai', 'Watson Pharma, Inc.', 'cranshaw9@ibm.com', 'Annotés', '948-892-2167', null, 10, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('3 Pond Terrace', 'Cauayan', 'Apotex Corporation', 'kbabara@ox.ac.uk', 'Åsa', '274-618-5207', '6112', 9, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('9 Lakewood Gardens Place', 'Mayo', 'Qualitest Pharmaceuticals', 'rcitrineb@fc2.com', 'Béatrice', '380-372-4930', '94140', 2, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('8 Rutledge Park', 'Grzmiąca', 'Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', 'feskellc@so-net.ne.jp', 'Anaïs', '872-897-0663', '78-450', 6, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('69867 Northfield Alley', 'Utarapasar', 'Koh Gen Do USA, Inc', 'bbowlesd@epa.gov', 'Lucrèce', '997-486-7518', null, 4, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('23 Basil Parkway', 'Qingliu', 'L. Perrigo Company', 'jarisse@google.com', 'Ruò', '236-274-3613', null, 6, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('97 Pepper Wood Avenue', 'Atami', 'Contract Pharmacy Services-PA', 'ssheehanf@xrea.com', 'Maëlla', '251-293-7780', '413-0033', 3, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('6 Forest Circle', 'Dahuangwei', 'Torrent Pharmaceuticals Limited', 'hcalfg@domainmarket.com', 'Märta', '803-278-4388', null, 5, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('4375 Jenna Terrace', 'Daniwato', 'Zep Inc.', 'ktimmesh@mayoclinic.com', 'Kévina', '811-813-8267', null, 8, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('6 Morrow Road', 'Leonidovo', 'Rebel Distributors Corp', 'ugorei@fema.gov', 'Réservés', '356-714-7570', '694230', 2, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('38161 Sugar Plaza', 'Pirapo', 'Johnson & Johnson Healthcare Products, Division of McNEIL-PPC, Inc.', 'kblucherj@army.mil', 'Ráo', '543-536-4297', null, 5, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('04 Emmet Point', 'Limon', 'Ulta', 'lpichefordk@zdnet.com', 'Ophélie', '962-206-1474', '6530', 7, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('655 Cody Terrace', 'Redinha', 'Golden State Medical Supply, Inc.', 'blakelandl@senate.gov', 'Mélys', '717-973-2541', '3105-325', 10, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('111 Russell Trail', 'Luofang', 'Lineage Therapeutics', 'bpedwellm@umn.edu', 'Kuí', '473-762-4874', null, 4, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('411 Bowman Plaza', 'Heping', 'Apotex Corp', 'scharnleyn@hao123.com', 'Cécile', '797-128-1819', null, 9, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('70953 Roxbury Point', 'Shimodate', 'Vitality Works, Inc.', 'xlarwayo@domainmarket.com', 'Zoé', '110-817-4453', '309-1127', 7, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('3301 Hoepker Trail', 'Hanggan', 'AvPAK', 'hsheldrakep@sphinn.com', 'Thérèse', '315-851-6530', '6406', 1, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('1607 Novick Hill', 'Töreboda', 'MEGASOL COSMETIC GMBH', 'arhodefq@devhub.com', 'Lucrèce', '639-371-5034', '545 30', 6, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('5 Alpine Point', 'Contagem', 'Melaleuca Inc.', 'rdashperr@addtoany.com', 'Méryl', '473-598-6786', '32000-000', 10, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('44491 Tony Center', 'Niort', 'Sato Pharmaceutical Co., Ltd.', 'wrigebys@kickstarter.com', 'Ruì', '250-797-4117', '79021 CEDEX', 10, 1);
# insert into customers (address, city, company_name, email, person_contact, phone, postcode, company_id, is_active) values ('272 Scofield Avenue', 'Modot', 'Cardinal Health', 'gnaisbittt@youku.com', 'Maëlla', '219-154-5642', null, 6, 1);

insert into un_table (id, un_number, un_name_and_description, un_labels, un_packing_group) values (1, 1263, 'PAINT', '3', 'I');
insert into un_table (id, un_number, un_name_and_description, un_labels, un_packing_group) values (2, 1263, 'PAINT RELATED MATERIAL', '3', 'I');
insert into un_table (id, un_number, un_name_and_description, un_labels, un_packing_group) values (3, 1263, 'PAINT', '3', 'II');
insert into un_table (id, un_number, un_name_and_description, un_labels, un_packing_group) values (4, 1263, 'PAINT RELATED MATERIAL', '3', 'II');
insert into un_table (id, un_number, un_name_and_description, un_labels, un_packing_group) values (5, 1263, 'PAINT', '3', 'III');
insert into un_table (id, un_number, un_name_and_description, un_labels, un_packing_group) values (6, 1263, 'PAINT RELATED MATERIAL', '3', 'III');
insert into un_table (id, un_number, un_name_and_description) values (7, 4850, 'Namfix');
insert into un_table (id, un_number, un_name_and_description) values (8, 8542, 'Flowdesk');
insert into un_table (id, un_number, un_name_and_description) values (9, 4223, 'Konklux');
insert into un_table (id, un_number, un_name_and_description) values (10, 8412, 'Aerified');
insert into un_table (id, un_number, un_name_and_description) values (11, 5041, 'Alpha');
insert into un_table (id, un_number, un_name_and_description) values (12, 9939, 'Fintone');
insert into un_table (id, un_number, un_name_and_description) values (13, 5136, 'Fintone');
insert into un_table (id, un_number, un_name_and_description) values (14, 3401, 'Cardguard');
insert into un_table (id, un_number, un_name_and_description) values (15, 8131, 'Trippledex');
insert into un_table (id, un_number, un_name_and_description) values (16, 4770, 'Andalax');
insert into un_table (id, un_number, un_name_and_description) values (17, 9739, 'Stringtough');
insert into un_table (id, un_number, un_name_and_description) values (18, 3652, 'Andalax');
insert into un_table (id, un_number, un_name_and_description) values (19, 6902, 'Home Ing');
insert into un_table (id, un_number, un_name_and_description) values (20, 4250, 'Latlux');
insert into un_table (id, un_number, un_name_and_description) values (21, 4986, 'Tampflex');
insert into un_table (id, un_number, un_name_and_description) values (22, 2687, 'Temp');
insert into un_table (id, un_number, un_name_and_description) values (23, 9506, 'Home Ing');
insert into un_table (id, un_number, un_name_and_description) values (24, 4681, 'Zamit');
insert into un_table (id, un_number, un_name_and_description) values (25, 1897, 'Flexidy');
insert into un_table (id, un_number, un_name_and_description) values (26, 6314, 'Konklux');
insert into un_table (id, un_number, un_name_and_description) values (27, 2606, 'Sub-Ex');
insert into un_table (id, un_number, un_name_and_description) values (28, 9559, 'Treeflex');
insert into un_table (id, un_number, un_name_and_description) values (29, 7794, 'Ventosanzap');
insert into un_table (id, un_number, un_name_and_description) values (30, 9543, 'Tampflex');
#
# # INSERT INTO adr_lists_entity (id, company, customer, first_name, last_name, un_rows) VALUES (1, '{"id": 1, "city": "Otrokovice", "email": "btissiman0@noaa.gov", "phone": "+420 827 667 2354", "address": "44 Clarendon Court", "postCode": "765 02", "companyName": "Yambee", "referenceNo": "59-478-6950", "personContact": "Booth Tissiman"}', '{"id": 6, "city": "Vimmerby", "email": "lstefanovic5@dagondesign.com", "phone": "724-852-0974", "address": "00821 Continental Terrace", "postCode": "598 24", "referenceNo": null, "customerName": "Laboratoires Dermo Cosmetik Inc.", "personContact": "Esbjörn"}', '', 'Davidovitchddddddd', '[{"unDesc": "", "unList": [{"id": 1, "unNumber": "5912", "descriptionUn": "Bytecard"}]}]');
#
#
# # INSERT INTO adr_list.delivery_notes (id, company_id, created_on, customer_id, delivery_note_form, is_active, updated_on, user_id) VALUES (1, 1, '2021-05-28 18:45:39', 1, '{"company": {"id": 1, "city": "Otrokovice", "email": "btissiman0@noaa.gov", "phone": "+420 827 667 2354", "active": true, "address": "44 Clarendon Court", "postCode": "765 02", "companyName": "Yambee", "referenceNo": "59-478-6950", "personContact": "Booth Tissiman"}, "unForms": [{"unDesc": null, "unList": [{"id": 1, "labels": "3", "unClass": null, "unNumber": "1263", "hazardIdNo": null, "adrTankCode": null, "packingGroup": "I", "specialPFCBulk": null, "adrTankSpecialP": null, "packagingMixedPP": null, "specialPFCLoading": null, "transportCategory": null, "classificationCode": null, "limitedQuantityVol": null, "nameAndDescription": "PAINT", "packagingSpecialPP": null, "specialPFCPackages": null, "limitedQuantityCode": null, "specialPFCOperation": null, "packagingInstructions": null, "portableTanksSpecialP": null, "vehicleForTankCarriage": null, "portableTanksInstructions": null}], "quantityAll": 30, "packagingList": [{"id": 2, "codePackaging": "3H1", "descriptionPackaging": "kanister"}], "quantityPiece": 2}], "customer": {"id": 1, "city": "Lapai", "email": "rchurly0@constantcontact.com", "phone": "725-493-5597", "address": "98 Shasta Street", "postCode": null, "referenceNo": null, "customerName": "Sandoz Inc", "personContact": "Cléa"}, "lastName": "Dalmanddddddddddddddddddddddddddd", "firstName": "Carolin77777777777777"}', true, null, null);

INSERT INTO packaging (id, code_packaging, description_packaging) VALUES (1, '1A2', 'bęben');
INSERT INTO packaging (id, code_packaging, description_packaging) VALUES (2, '3H1', 'kanister');
INSERT INTO packaging (id, code_packaging, description_packaging) VALUES (3, '1A1', 'bęben');
INSERT INTO packaging (id, code_packaging, description_packaging) VALUES (4, '3H1', 'kanister');

# insert into firma(firma_id, nazwa) values (1, 'nazwa1');
# insert into firma(firma_id, nazwa) values (2, 'nazwa2');
# insert into firma(firma_id, nazwa) values (3, 'nazwa3');

INSERT INTO deliveries (id, company_address, company_city, company_country, company_id, company_name, company_postcode, customer_address, customer_city, customer_country, customer_id, customer_name, customer_postcode, description_delivery, driver_document, driver_name, point_class0, point_class1, point_class2, point_class3, point_class4, points, transportation, truck_description, truck_number, type_activities) VALUES (1, '44 Clarendon Court', 'Otrokovice', null, 1, 'Yambee', '765 02', '98 Shasta Street', 'Lapai', null, 1, 'Sandoz Inc', null, null, 'DWR22222', 'Michał', null, 6012, 0, 0, null, 6012, null, 'dsdsdsds', 'DWR333222', null);

INSERT INTO material_rows (id, packaging_code, packaging_description, packaging_id, quantity_all, quantity_piece, quantity_point, un_class, un_id, un_labels, un_name_and_description, un_number, un_packing_group, delivery_id) VALUES (1, '1A2', 'bęben', 1, 20, 100, null, null, 1, '3', 'PAINT', '1263', 'I', 1);
INSERT INTO material_rows (id, packaging_code, packaging_description, packaging_id, quantity_all, quantity_piece, quantity_point, un_class, un_id, un_labels, un_name_and_description, un_number, un_packing_group, delivery_id) VALUES (2, '3H1', 'kanister', 2, 2000, 10, null, null, 2, '3', 'PAINT RELATED MATERIAL', '1263', 'I', 1);
INSERT INTO material_rows (id, packaging_code, packaging_description, packaging_id, quantity_all, quantity_piece, quantity_point, un_class, un_id, un_labels, un_name_and_description, un_number, un_packing_group, delivery_id) VALUES (3, '3H1', 'kanister', 4, 1400, 22, null, null, 6, '3', 'PAINT RELATED MATERIAL', '1263', 'III', 1);